name: Publish to AUR

on:
  push:
    branches: [main]
    paths: [PKGBUILD, .SRCINFO]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, 'Update to')
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Publish to AUR
        uses: KSXGitHub/github-actions-deploy-aur@v3.0.1
        with:
          pkgname: linux-galaxyaudio
          pkgbuild: ./PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: "Update to $(grep pkgver= PKGBUILD | cut -d= -f2)"
          assets: |
            PKGBUILD
            .SRCINFO
            linux-galaxyaudio.install
            config
            max98390-sound.patch
